apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcloud-sqlproxy.fullname" . }}
  annotations:
  {{- if .Values.service.internalLB  }}
    cloud.google.com/load-balancer-type: "Internal"
  {{- end }}
  {{- range  $key, $value := .Values.service.annotations  }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    {{- include "gcloud-sqlproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  {{- range .Values.cloudsql.instances }}
  - name: {{ .instanceShortName | default (.instance | trunc 15) }}
    protocol: TCP
    port: {{ .port }}
    targetPort: {{ .instanceShortName | default (.instance | trunc 15) }}
  {{- end }}
  selector:
    {{- include "gcloud-sqlproxy.selectorLabels" . | nindent 4 }}
